# Site settings
title: David C. Lafferty
email: davidcl2@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  David C. Lafferty is a Ph.D. candidate in the Departmenr of Atmospheric Sciences
  at the University of Illinois at Urbana-Champaign. David's research interests
  includes climate change and its relation to multi-sector dynamics and decision-making
  under uncertainty.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://david0811.github.io" # the base hostname & protocol for your site
twitter_username: DavidCLafferty
github_username:  david0811
orcid_id: 0000-0003-2098-6885
google_scholar_id: Kpwu3qEAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Ph.D. candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
